spring.application.name=spring-advance-assignment

# H2 Database
# spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.url=jdbc:h2:file:/app/data/tododb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=naman
spring.datasource.password=naman123

# Ensure data.sql runs after table creation
spring.jpa.defer-datasource-initialization=true

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true


spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://ems_keycloak:8080/realms/ems-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/ems-realm

# H2 Console: http://localhost:8080/h2-console