spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

spring.application.name=emp-backend
server.port=8081

# JDBC Connection configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# Spring Data JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring Security OAuth2 (Keycloak Verification)
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_ISSUER:}
